### ISSUE TITLE
Bash-4.4/OpenBSD-6.1 : `find: -regex: unknown option`

### ISSUE THREAD

**Issue by hs0ucy** [ShaneKilkelly/manuel-contrib-watch#4]
Hi,

When i'm running `manuel watch_assets_change`. 
I get that error : `find: -regex: unknown option`.

I don't have the problem on Linux.

Thanks for your code and your help!

**Comment by JuneKelly** [comment]
Hmm, it looks like `find` on openbsd just doesn't support the `-regex` flag (http://nixdoc.net/man-pages/OpenBSD/man1/find.1.html)

I'll see if I can come up with a fix that doesn't require that flag.

**Comment by hs0ucy** [comment]
@ShaneKilkelly Thanks to have accepted my pull request.
